/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./components/Breadcrumb.vue')['default']
    Controls: typeof import('./components/Controls.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Preview: typeof import('./components/Preview.vue')['default']
    Repeater: typeof import('./components/Repeater.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TemplateBody: typeof import('./components/TemplateBody.vue')['default']
    TemplateButtons: typeof import('./components/TemplateButtons.vue')['default']
    TemplateCategory: typeof import('./components/TemplateCategory.vue')['default']
    TemplateDetails: typeof import('./components/TemplateDetails.vue')['default']
    TemplateFooter: typeof import('./components/TemplateFooter.vue')['default']
    TemplateHeader: typeof import('./components/TemplateHeader.vue')['default']
  }
}
